title: EL ARMIA Mohammed
logo: Asset/el armia cv.jpeg
description: Incident| Problem Manager
#show_downloads: true
theme: jekyll-theme-minimal
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins
